CREATE DATABASE IF NOT EXISTS `INTERVENTIONS`;
USE `INTERVENTIONS`;

CREATE TABLE HistoMaj (
    CodeDoc VARCHAR(8) NOT NULL,
    NumLig INT NOT NULL,
    CodeElem VARCHAR(20) NOT NULL,
    Qte INT NOT NULL,
    Ignored TINYINT NOT NULL,
    DateMaj DATE NOT NULL,
    PRIMARY KEY (CodeDoc, NumLig)
)